[package]
name = "nabla-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The underlying proc-macro implementation for the `nabla` crate"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
## data structures

indexmap.workspace = true

## proc-macro deps

darling.workspace = true
# helps with debugging
macro-expander = { workspace = true, optional = true }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[features]
## unstable features (exempt from semver guarentees)

# Allow debugging macro expansion through the macro-expander crate
unstable-debug-expand = ["dep:macro-expander", "macro-expander/enable"]
